# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'Pics' do
    pod 'Parse'
end

target 'PicsTests' do

end

target 'PicsUITests' do

end

